server:
  port: 8081
spring:
  application:
    name: eureka-server-spring-cloud
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/